- name: restart_apache
  service: name=httpd state=restarted enabled=yes
- name: restart_memcached
  service: name=memcached state=restarted enabled=yes
- name: restart_mysqld
  service: name=mysqld state=restarted enabled=yes
